#!/bin/bash
## Try to download the file
wget -c -O phishtank-latest-db.json http://data.phishtank.com/data/online-valid.json

if [ ! -f ./phishtank-latest-db.json ]
then
    echo "Sorry wget did not seem to be able to download phishtank db"
else
    ./update-phishtank-rules
fi
